<?php 
$translations = array(
    "mainPage" => "Main Page",
    "contribute" => "Contribute",
    "about" => "About",
    "welcome" => "Welcome to the WYD Dictionary!",
    "welcomeContent" => "<p>Hello, nice to see you here! Since you're wisiting this page, you're probably willing to go to the World Youth Day and you want to check up some extra vocabulary - and that's great! We believe that having meaningfull conversations is one of the most important parts of the event, and we are here to help you prepare!</p><p>Choose two languages from the left menu and a list of available tarnslations for that pair will appear. You can further filter them by selecting tags (also from the left menu). You can also search by word, tarnslation, author or definition! You can also choose the level of the words you want to lern. If you wish, copy the URL of the webpage with all the weird-looking characters and you will be able to share your word list with your friends!</p><p>We also invite you to contribute! The dictionary would be empty without the help of many volounteers - you can become one of them! Head over to the <a href='#contribute'>contribute</a> section if you want to help us build the dict!</p>",
    "aboutContent" => "Hi, we are two young people from Poland!",
    "Search" => "Search",
    "SearchForWordDefLabel" => "Search for word, definition, label...",
    "Languages" => "Languages",
    "Tags" => "Tags",
    "firstChooseTheLanguages" => "Choose the languages above to get a list of available tags. If a pair of languages is not available, why not <a href='#contribute'>create it yourself?</a>",
    "Level" => "Level",
    "Word" => "Word",
    "Translation" => "Translation",
    "Definition" => "Definition",
    "Author" => "Author",
    "contributeHi" => "If you are willing to help us create the dictionary, please contact us at [email]. If you have already contacted us and you're willing to add your work, plese fill out the following form and we'll verify and add your records to the database as soon as possible!",
    "name" => "Name",
    "defaultLevel" => "Default level of the dictionary",
    "pin" => "Translator's PIN",
    "notANumber" => "This needs to be a number",
    "mail" => "E-mail adress",
    "fromLanguage" => "The base language of your dictionary ('from')",
    "toLanguage" => "The language into which you translate the words",
    "commonTags" => "If you want a tag to be added to all of the words in your dictionary, specify it here:",
    "tagName" => "The tag's short name",
    "tagReadable" => "The name visible to the user",
    "tagDescription" => "A longer tag description",
    "addTag" => "Add next tag...",
    "specialTags" => "If you specified any additional tags in the file you're uploading, please give their details down here:",
    "fileTransfer" => "Now add the file you prepared down here:",
    "readyToGo" => "You're ready to go! Just click the button: ",
    "send" => "Send",
    "columnSeparator" => "Column separator",
    "lineSeparator" => "Line separator",
    "separatorsExplanation" => "White characters: use \\n as new line (enter), \\t as tabulator and \\r as cariage return"
);
?>