<?php 
$translations = array(
    "code" => "en",
    "transAuthor" => "Jakub Dranczewski",
    "mainPage" => "Main Page",
    "contribute" => "Contribute",
    "about" => "About",
    "cookieConsent" => "We use cookies to make sure that the website works great. If you wish, you can disable them in the browser settings.",
    "okCookieConsent" => "Ok, great",
    "welcome" => "Welcome to the WYD Dictionary!",
    "welcomeContent" => "<p>Hello, nice to see you here! Since you're visiting this page, you're probably willing to go to the World Youth Day and you want to check up some extra vocabulary - and that's great! We believe that having meaningful conversations is one of the most important parts of the event, and we are here to help you prepare!</p><p>Choose two languages from the left menu and a list of available translations for that pair will appear. You can further filter them by selecting tags (also from the left menu). You can also search by word, translation, author or definition! You can also choose the level of the words you want to learn. If you wish, copy the URL of the web page with all the weird-looking characters and you will be able to share your word list with your friends!</p><p>We also invite you to contribute! The Dictionary would be empty without the help of many volunteers - you can become one of them! Head over to the <a href='#contribute'>contribute</a> section if you want to help us build the Dictionary!</p>",
    "aboutContent" => "<img class='fill' src='/img/logo.png' alt='logo'><p>Hi, we are two young people from Poland! We are very excited to join thousands of you at the World Youth Day in Krakow and we believe, that one of the most important aspects of this meeting is talking - about life, about faith, about the Bible, about pretty much anything! And if we want to have meaningful conversations about this topics, we need to work on our vocabulary.</p><p>We created this Dictionary for people who, just like us, would like to exchange thoughts during WYD and want to improve their language to do so. After many hours of hard work two platforms are ready - the web page for you to look through (and contribute to) the database and an advanced Python script to manage the all the data. Did we mention <a href='https://github.com/World-Youth-Days/Dictionary' target=_blank>it's all on GitHub</a>?</p><p>We hope that you'll find our work useful - and we also hope that you'll consider helping us make it even more awesome! Ho over to the <a href='#contribute'>\"Contribute\"</a> section to learn more about adding your translations to the Dictionary!</p><p>You cal always contact us at dict.wyd@gmail.com<br>Thanks for using our software!<br>Jakub Dranczewski & Hubert Bereś</p>",
    "nothingFound" => "Nothing found!",
    "nothingFoundTroubleshooting" => "Please refine your query or the hardness levels you've chosen!",
    "noWords" => "Nothing to show!",
    "noWordsTroubleshooting" => "We sadly don't have any words to show you for the selected pair of languages. Maybe trying choosing them the other way round will help?<br><br>There's also another fix for this situation! <a href='#contribute'>Help us and create the translations yourself!</a>",
    "Search" => "Search",
    "SearchForWordDefLabel" => "Search for word, definition, label...",
    "Languages" => "Languages",
    "Tags" => "Tags",
    "firstChooseTheLanguages" => "Choose the languages above to get a list of available tags. If a pair of languages is not available, why not <a href='#contribute'>create it yourself?</a>",
    "Level" => "Level",
    "Word" => "Word",
    "Translation" => "Translation",
    "Definition" => "Definition",
    "Author" => "Author",
    "contributeHi" => "If you want to help create the Dictionary, that's great! You can find the instructions <a href='instructions/pl.pdf' target=_blank>here</a>. Please follow them carefully - the process is easier than it seems! Should you have any problems, we're accessible at dict.wyd[at]gmail.com.<br><br>Please note that the first time you use the following form to send us your translations, you actually create an account - remember the mail and PIN, because they will be later used to verify your personality ;) All the details will also be send to the email address you provide.",
    "name" => "Name",
    "defaultLevel" => "Default level of the dictionary",
    "pin" => "Translator's PIN",
    "notANumber" => "This needs to be a number",
    "mail" => "E-mail address",
    "fromLanguage" => "The base language of your dictionary ('from')",
    "toLanguage" => "The language into which you translate the words",
    "commonTags" => "If you want a tag to be added to all of the words in your dictionary, specify it here:",
    "tagName" => "The tag's short name",
    "tagReadable" => "The name visible to the user",
    "tagDescription" => "A longer tag description",
    "addTag" => "Add next tag...",
    "specialTags" => "If you specified any additional tags in the file you're uploading, please give their details down here:",
    "fileTransfer" => "Now add the file you prepared down here:",
    "readyToGo" => "You're ready to go! Just click the button: ",
    "send" => "Send",
    "columnSeparator" => "Column separator",
    "lineSeparator" => "Line separator",
    "separatorsExplanation" => "White characters: use \\n as new line (enter), \\t as tabulator and \\r as carriage return"
);
?>
