<?php 
$translations = array(
    "code" => "pl",
    "transAuthor" => "Hubert Bereś",
    "mainPage" => "Strona Główna",
    "contribute" => "Współtwórz",
    "about" => "O Słowniku",
    "cookieConsent" => "Używamy plików cookie by zapewnić optymalną funkcjonalność strony. Zawsze możesz wyłączyć je w ustawieniach przeglądarki..",
    "okCookieConsent" => "Ok",
    "welcome" => "Witaj w Słowniku ŚDM!",
    "welcomeContent" => "<p>Witaj, miło Cię widzieć. Skoro odwiedzasz tę stornę, pewnie szukasz okazji, by poszerzyć słownictwo przed Światowymi Dniami Młodzieży - to świetnie! Sądzimy, że jednym z ważniejszych aspektów tego wydarzenia okażą się nowe znajomości, a to oznacza jedno: rozmowy w obcych językach. Stworzyliśmy tę stronę, by pomóc Ci się do nich przygotować.</p><p>Wybierz dwa języki w menu po lewej, żeby zobaczyć dostępne dla nich tłumaczenia. Możesz je przefiltrować wybierając tagi (także z menu po lewej), lub po prostu wyszukać potrzebne słowo, tłumaczenie czy autora. Warto wybrać też orientacyjny poziom trudności wyświetlanych słówek. Jeśli chcesz udostępnić wynik wyszukiwania, skopiuj adres URL strony razem z dziwnymi znaczkami na końcu ;)</p><p>Zapraszamy Cię również do współtworzenia Słownika! Byłby pusty bez pomocy wolontariuszy - możesz zostać jednym z nich! Przejdź do zakładki <a href='#contribute'>Współtwórz</a> jeśli chcesz zacząć dodawać tłumaczenia</p>",
    "aboutContent" => "<img class='fill' src='/img/logo.png' alt='logo'><p>Cześć! Jesteśmy dwójką młodych programistów z Polski! Nie możemy się doczekać, aby spotkać tysiące z Was na Światowych Dniach Młodzieży w Krakowie i mamy nadzieję, że czeka nas w związku z tym wiele interesujących konwersacji - o życiu, o wierze, o Biblii i wszystkich innych rzeczach, jakie tylko przyjdą nam do głowy. Jeśli chcemy, by rozmowy okazały się konstruktywne, warto popracować wcześniej nad słownictwem.</p><p>Stworzyliśmy ten Słownik dla ludzi, który tak jak my chcą poprawić swoje zdolności językowe. Po wieeelu godzinach ciężkiej pracy gotowe powstały dwie platformy: strona internetowa, którą oglądasz, oraz baza danych (wraz z skryptem w Pythonie), gdzie bezpiecznie przechowujemy wszystkie nadesłane tłumaczenia. Wspominaliśmy już, że <a href='https://github.com/World-Youth-Days/Dictionary' target=_blank>jesteśmy na GitHubie</a>?</p><p>Mamy nadzieję, że nasza praca będzie dla Ciebie użyteczna - a także że rozważysz swój własny wkład w tłumaczenia, aby uczynić ją jeszcze bardziej przydatną. Przejdź do zakładki <a href='#contribute'>\"Współtwórz\"</a> aby dowiedzieć się więcej o tłumaczeniach, które możesz umieścić w Słowniku.</p><p>Jeśli masz pytania, jesteśmy dostępni pod adresem dict.wyd@gmail.com<br>Dziękujemy za skorzystanie z naszego produktu!<br>Jakub Dranczewski & Hubert Bereś</p>",
    "nothingFound" => "Nic tu nie ma!",
    "nothingFoundTroubleshooting" => "Popraw proszę swoje wyszukiwanie albo zmień zakres poziomu trudności...",
    "noWords" => "Nic tu nie ma...",
    "noWordsTroubleshooting" => "Niestety nie mamy żadnych słówek do pokazania w tej kombinacji języków. Może spróbujesz wybrać inną parę?<br><br>Jest też inne rozwiązanie tego problemu ;) <a href='#contribute'>Sam dodaj brakujące tłumaczenie!</a>",
    "Search" => "Szukaj",
    "SearchForWordDefLabel" => "Wyszukaj słowo, definicję, opis...",
    "Languages" => "Języki",
    "Tags" => "Tagi",
    "firstChooseTheLanguages" => "Wybierz języki powyżej, by wyświetlić listę dostępnych tagów. Jeśli tłumaczenie nie jest jeszcze dostępne, dlaczego nie <a href='#contribute'>stworzysz go teraz?</a>",
    "Level" => "Poziom trudności",
    "Word" => "Słowo",
    "Translation" => "Tłumaczenie",
    "Definition" => "Definicja",
    "Author" => "Autor",
    "contributeHi" => "Jeśli chcesz pomóc w tworzeniu Słownika, świetnie się składa! Możesz znaleźć potrzebne instrukcje <a href='instructions/pl.pdf' target=_blank>tutaj</a>. Przeczytaj je uważnie, a stanie się to prostsze niż myślisz. Jeśli masz jakieś trudności, jesteśmy dostępni pod dict.wyd[at]gmail.com.<br><br>Zauważ, że korzystając z tego formularza po raz pierwszy, zakładasz konto na naszej stronie - zapamiętaj podany e-mail i PIN. Będziemy ich używać, żeby upewnić się, że Ty to Ty ;) Te dane zostaną także przekazane na podany adres e-mail.",
    "name" => "Nazwa użytkownika",
    "defaultLevel" => "Domyślny poziom Twoich słówek",
    "pin" => "Twój PIN",
    "notANumber" => "To musi być liczba!",
    "mail" => "Adres e-mail",
    "fromLanguage" => "Wyjściowy język Twoich słówek ('from')",
    "toLanguage" => "Język, na który tłumaczysz",
    "commonTags" => "Jeśli chcesz dodać tag do wszystkich wysyłanych słówek, wpisz go tutaj:",
    "tagName" => "Krótka nazwa tagu",
    "tagReadable" => "Nazwa, którą zobaczą użytkownicy",
    "tagDescription" => "Opis tagu",
    "addTag" => "Dodaj kolejny tag...",
    "specialTags" => "Jeśli używasz dodatkowych tagów w wysyłanym pliku, tutaj możesz dodać ich opisy:",
    "fileTransfer" => "Teraz załącz przygotowany plik z tłumaczeniami:",
    "readyToGo" => "Gotowe! Wystarczy kliknąć: ",
    "send" => "Wyślij",
    "columnSeparator" => "Rozdzielacz kolumn",
    "lineSeparator" => "Rozdzielacz linii",
    "separatorsExplanation" => "Białe znaki: użyj \\n jako nowej linii (enter), \\t jako tabulatora oraz \\r jako 'powrót karetki'"
);
?>
